name: Deploy package to GitHub package repository
'on':
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: |
          echo "registry=https://registry.npmjs.org
          //npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN
          @jenyus-org:registry=https://npm.pkg.github.com
          always-auth=true" > ~/.npmrc
          npm ci
        working-directory: ./nestjs-graphql-utils
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - run: npm install
        working-directory: ./nestjs-graphql-utils
      - run: npm test
        working-directory: ./nestjs-graphql-utils
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com
          package: ./nestjs-graphql-utils/package.json
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./nestjs-graphql-utils/package.json
          access: public
